<a href="https://colab.research.google.com/github/cp612sh/2048/blob/master/pytorch_60mins.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pytorch 1.3.0 

开始

##Tensor

In [0]:
import torch

In [3]:
x = torch.empty(5,3) # 未初始化
print(x)

tensor([[2.3541e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [4]:
rx = torch.rand(5,3) # 随机
print(rx)

tensor([[0.6805, 0.6361, 0.7077],
        [0.1973, 0.4288, 0.9066],
        [0.0458, 0.2461, 0.7192],
        [0.9192, 0.8576, 0.6245],
        [0.4574, 0.6545, 0.9929]])


In [6]:
zx = torch.zeros(5,3,dtype=torch.long) # 类型为long的全零
print(zx)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
dx = torch.tensor([5.5,3]) # 直接从数据构建Tensor
print(dx)

tensor([5.5000, 3.0000])


In [8]:
# 从已有的Tensor中创建Tensor
# new_* 方法
x = x.new_ones(5,3, dtype=torch.double)
print(x)

# rand like
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.0744, 0.1737, 0.3313],
        [0.7318, 0.5387, 0.2123],
        [0.1027, 0.8573, 0.5229],
        [0.1631, 0.1374, 0.9943],
        [0.4395, 0.8733, 0.8431]])


In [10]:
print(x.size()) 

torch.Size([5, 3])


## Operations

In [11]:
y = torch.rand(5,3)
print(x + y)

tensor([[0.5833, 0.3616, 0.9108],
        [0.9666, 1.2862, 0.7426],
        [0.6659, 1.7698, 1.0953],
        [0.5931, 1.0894, 1.2041],
        [0.7031, 1.3008, 1.6329]])


In [12]:
print(torch.add(x,y)) # another add

tensor([[0.5833, 0.3616, 0.9108],
        [0.9666, 1.2862, 0.7426],
        [0.6659, 1.7698, 1.0953],
        [0.5931, 1.0894, 1.2041],
        [0.7031, 1.3008, 1.6329]])


In [13]:
result = torch.empty(5,3)
torch.add(x,y,out=result) 
print(result)

tensor([[0.5833, 0.3616, 0.9108],
        [0.9666, 1.2862, 0.7426],
        [0.6659, 1.7698, 1.0953],
        [0.5931, 1.0894, 1.2041],
        [0.7031, 1.3008, 1.6329]])


In [14]:
# add x to y
y.add_(x)
print(y)

tensor([[0.5833, 0.3616, 0.9108],
        [0.9666, 1.2862, 0.7426],
        [0.6659, 1.7698, 1.0953],
        [0.5931, 1.0894, 1.2041],
        [0.7031, 1.3008, 1.6329]])


In [15]:
print(x[:,1])

tensor([0.1737, 0.5387, 0.8573, 0.1374, 0.8733])


In [17]:
# resizing with torch.view
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # -1 is inferred from other denmentions

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8379])
-0.8378638625144958


In [21]:
a = torch.ones([5])
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
print(torch.cuda.is_available())

True


In [29]:
if torch.cuda.is_available():
  device = torch.device("cuda") # a CUDA device object
  y = torch.ones_like(x, device=device) # 直接在CUDA设备上创建Tensor
  x = x.to(device) # 也可以用 cuda 字符串
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))

tensor([0.1621], device='cuda:0')
tensor([0.1621], dtype=torch.float64)
